### PR TITLE
use Dotty-native build of cats

### PR DESCRIPTION
**Pull request by larsrh**
This currently doesn't work:

* sjs1 artifacts cannot be resolved for Dotty (:eyes: @djspiewak)
* compile error in core (see below)

```
[info] compiling 78 Scala sources and 1 Java source to /home/lars/proj/typelevel/cats-effect/core/jvm/target/scala-0.27/classes ...
[error] undefined: new simulacrum.noop # 216316: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),module simulacrum),noop),<init>) at sbt-api
[warn] sbt-api: Unhandled type class dotty.tools.dotc.core.Types$$anon$7 : <error undefined: new simulacrum.noop # 216316: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),module simulacrum),noop),<init>) at sbt-api>

```

### CODE REVIEW

**Comment by vasilmkd** [comment]
@larsrh Some of this could be my fault, I was desperately trying to get cats-effect to compile on Dotty 0.26.0 which didn't support ScalaJS, looking into this now.
