### ISSUE TITLE
`Uncaught TypeErrror` in browser console after upgrading to 3.3.3

### ISSUE THREAD

**Issue by toddburnside** [typelevel/cats-effect#2730]
After upgrading from 3.3.2 to 3.3.3 I started seeing error messages in the browser console on startup. The message is of the form `Uncaught TypeError: f$1 is not a function`.

One of the lines of code in the callstack is
```
hardExit$3.apply$mcVI$sp__I__V(c.Lcats_effect_ExitCode__f_code)
```
With the line above it is:
```
var c = $j_cats$002eeffect$002eExitCode.$as_Lcats_effect_ExitCode(c$2);
 hardExit$3.apply$mcVI$sp__I__V(c.Lcats_effect_ExitCode__f_code)
```
This looks similar to this line of code from #2707: https://github.com/typelevel/cats-effect/blob/614e98982602263d1447f3a9975be84bb4c23a67/core/js/src/main/scala/cats/effect/IOApp.scala#L243

I haven't been able to verify it is the problem, but the cats effect upgrade is the only change. If needed, I could try to create a minimal example. The application it is occurring in does not qualify as simple...

**Comment by armanbilge** [comment]
Thanks for the report! I suspect the changes I made in https://github.com/typelevel/cats-effect/pull/2707 as well.

Just to clarify, is the application completely breaking? Or is it just the error message in the log. I want to make sure we can catch this sort of thing in CI.

For browsers users of CE, it should be fine to stay on 3.3.2 until this is fixed; the only changes in 3.3.3 were affecting the JVM and Node.js runtimes.

**Comment by toddburnside** [comment]
Ah, yes, I should have clarified. Everything appears to be working correctly - there is just the message in the log. Thanks.

**Comment by armanbilge** [comment]
Aha, good to know :) thanks for the fast reply.

**Comment by armanbilge** [comment]
Sorry, I'm going to need help reproducing this :) I tried a few easy things:

```scala
// using scala 2.13
// using scala-js
// using lib org.typelevel::cats-effect_sjs1:3.3.3

import cats.effect._

object Main extends IOApp.Simple {
  // def run = IO.println("hello world")
  // def run = IO.raiseError(new Exception)
  // def run = IO.canceled
  def run = IO.never
}
```
```html
<body>
  hello world
  <script src="i2730.js"></script>
</body>
```

But neither of these seems sufficient to reproduce in Firefox anyway.

**Comment by toddburnside** [comment]
I'm probably not going to get a chance to look at it tonight, but I'll try to reproduce it in the morning.

**Comment by toddburnside** [comment]
It took awhile to isolate it, but it appears the problem is related to our use of `vite` in our pipeline. Vite is providing a `process` that seems to be interfering with Cats Effect's use of `js.Dynamic.global.process` via `hardExit`.  I think #2707 just uses it in a few more places and we just happened to hit the problem now. This doesn't seem to be a bug with Cats Effect, so I think this issue can be closed. If I come up with more useful information, I'll add it to this issue in case it helps others.

**Comment by armanbilge** [comment]
Thanks for the update and your efforts to track this down! I'd still like to try and fix this if possible. I wonder if we need another `Try` somewhere to gracefully swallow this error. Actually, I think I know what is wrong... this was helpful, thanks :)

**Comment by armanbilge** [comment]
For the record, this was not specific to `vite`, it was a bug in CE, and completely my bad :) easy fix tho.

**Comment by toddburnside** [comment]
Happy to have been of some assistance. I'm also glad it was an easy fix. I published your PR locally and the error no longer occurs. Your fix make sense.  👍 It seems obvious in hindsight, doesn't it. 😄

**Comment by armanbilge** [comment]
Ah, perfect, thanks for confirming! I was able to make a reproducer for CI, so never again. It was obvious, sorry to send you down the rabbit hole 😅 🤦

**Comment by toddburnside** [comment]
No worries. Thanks for the fix. :)

**Comment by cquiroz** [comment]
Cool, thanks @armanbilge, it seems relying on `process` is going to be problemmatic in browsers in general?

**Comment by armanbilge** [comment]
@cquiroz yes, `process` is a tricky one. We mostly use it so that `IOApp` on Node.js can behave like the JVM: command line args, signal handlers, exit hooks, etc.

But, `process.env` specifically has become a sort of pseudo-standard across web frameworks as well:
- https://create-react-app.dev/docs/adding-custom-environment-variables/
- https://webpack.js.org/plugins/environment-plugin/
- https://vitejs.dev/guide/env-and-mode.html#production-replacement

Enough so, that we also use it for configuring the CE runtime on JS:
https://typelevel.org/cats-effect/docs/scaling-and-tuning/io-runtime-config#js

So, we have to resort to `js.Dynamic` and `Try` when working with `process`, and rely on our test suite to make sure we didn't forget any `Try` 😬 

Maybe a more robust approach would be to first detect globally if we are running in Node.js, and then use that to decide whether or not to do all those Node.js-only `process` things. Then if we forget to wrap something in a `Try` like I did here it is much less likely to create a problem.

```scala
val isNodeJSRuntime = Try(
  js.Dynamic.global.process.release.name.asInstanceOf[String]
).toOption.exists(_ == "node")
```
