### ISSUE TITLE
timeout and product aren't resolved on Resource[F, *] for ce3+scala_2.12

### ISSUE THREAD

**Issue by nikiforo** [typelevel/cats-effect#2763]
Minimization:
* fork project: https://github.com/nikiforo/ce3res
* launch sbt
* sbt:ce3res> compile
* Notice that the project compiles
* sbt:ce3res> + compile
* Notice
```
[error] /ce3res/src/main/scala/name/nikiforo/ce3res/Main.scala:15:21: value product is not a member of cats.effect.Resource[cats.effect.IO,Int]
[error]     val res2 = res1.product(res1)
[error]                     ^
[error] /ce3res/src/main/scala/name/nikiforo/ce3res/Main.scala:16:21: value timeout is not a member of cats.effect.Resource[cats.effect.IO,Int]
[error]     val res3 = res1.timeout(1.second)
[error]                     ^
```

Additional info:
* `tupleLeft` isn't resolved as well
* `product` works in ce2 for scala_2.12

**Comment by djspiewak** [comment]
You're missing `-Ypartial-unification` in your `scalacOptions`. :-) That's why it doesn't compile on 2.12. When I add that option, your reproduction `+compile`s successfully.
